language: c
compiler:
 - clang
 - gcc
before_script:
 - sudo apt-get install libevent-dev
 - curl https://download.libsodium.org/libsodium/releases/LATEST.tar.gz | tar -xvzf -
 - cd libsodium-stable
 - ./configure
 - make && make check
 - sudo make install
 - sudo ldconfig
 - cd ..
script:
 - autoreconf -vi
 - ./configure
 - make
 - sudo ./hack/setup-travis.sh
 - cd tests && bundle install && make test
