#!/bin/sh
# Generate version automatically.

echo "/* Automatically generated by $0 */
#ifndef VERSION_H
#define VERSION_H
"

version=$(git describe --match "v[0-9]*" | sed -e 's/-/./g' | sed -e 's/^v//g')

echo "const char *the_version = \"$version\";"
echo ""

echo "#endif"
