#!/bin/sh
# Generate version automatically.

version=$(git describe --always --match "v[0-9]*" | sed -e 's/-/./g' | sed -e 's/^v//g')
version_file=version.h

if test -f "$version_file"; then
    VC=$(sed -nr 's/.*the_version = "(.*)".*/\1/p' $version_file)
else
    VC=unset
fi

if test "$VC" != "$version"; then
    echo "/* Automatically generated by $0 */
#ifndef VERSION_H
#define VERSION_H

const char *the_version = \"$version\";

#endif" > $version_file
fi
