#!/bin/sh -e

mkdir -p bin

echo '#!/bin/sh' > bin/okabi
echo 'echo local' >> bin/okabi

exec < c
echo '#!/bin/sh' > bin/okc-local
while read compiler; do
  $compiler lib.c main.c -o test-c || continue
  echo "echo $compiler" >> bin/okc-local
done
 
echo '#!/bin/sh' > bin/okcpp-local

echo '#!/bin/sh' > bin/oklibs-local
echo 'echo "  -pie -L/usr/local/lib  -framework CoreFoundation -framework CoreServices"' >> bin/oklibs-local

echo '#!/bin/sh' > bin/okar-local
echo 'exec ar "$@"' >> bin/okar-local

echo '#!/bin/sh' > bin/okranlib-local
echo 'exec ranlib "$@"' >> bin/okranlib-local

chmod +x bin/ok*
